parameters:
#    images.example.class: Images\ImagesBundle\Example

services:
#    images.example:
#        class: %images.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    redirectionListener:
        class: Images\ImagesBundle\Listener\RedirectionListener
        arguments: [@service_container, @session]
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }