<?php

namespace Images\ImagesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MurRepository extends EntityRepository
{
	public function listeGlobale() {
		$qb = $this->createQueryBuilder('alias')
			->select('alias')
			->orderBy('alias.id', 'DESC');
		return $qb->getQuery()->getResult();
	}
}
